import type { RawWord } from '../lib/types';

type CoverageWordSpec = {
  pt: string;
  en: string;
  forms?: string[];
  difficulty?: 1 | 2 | 3 | 4 | 5;
  difficultForEnglish?: boolean;
};

const COVERAGE_WORD_SPECS: CoverageWordSpec[] = [
  { pt: 'delícia', en: 'delight / deliciousness' },
  { pt: 'sal', en: 'salt' },
  { pt: 'brasileira', en: 'Brazilian (fem.)' },
  { pt: 'pessoas', en: 'people' },
  { pt: 'gás', en: 'gas' },
  { pt: 'apimentada', en: 'spicy (fem.)' },
  { pt: 'comi', en: 'I ate' },
  { pt: 'salgada', en: 'salty / savory (fem.)' },
  { pt: 'satisfeito', en: 'satisfied' },
  { pt: 'pizza', en: 'pizza' },
  { pt: 'alergia', en: 'allergy' },
  { pt: 'camarão', en: 'shrimp' },
  { pt: 'garçom', en: 'waiter' },
  { pt: 'tomou', en: 'took / had / drank' },
  { pt: 'gostoso', en: 'tasty' },
  { pt: 'bife', en: 'steak' },
  { pt: 'passado', en: 'done / cooked' },
  { pt: 'brigadeiro', en: 'brigadeiro' },
  { pt: 'leite', en: 'milk' },
  { pt: 'glúten', en: 'gluten' },
  { pt: 'dividir', en: 'to split / to share' },
  { pt: 'fresco', en: 'fresh' },
  { pt: 'pedido', en: 'order' },
  { pt: 'laranja', en: 'orange' },
  { pt: 'coloca', en: 'put / set' },
  { pt: 'dieta', en: 'diet' },
  { pt: 'aquele', en: 'that one' },
  { pt: 'guardanapos', en: 'napkins' },
  { pt: 'feijoada', en: 'feijoada' },
  { pt: 'conseguem', en: 'can / are able to' },
  { pt: 'goste', en: 'like (subjunctive)' },
  { pt: 'volto', en: 'I return / I come back' },
  { pt: 'atendimento', en: 'service / customer service' },
  { pt: 'for', en: 'be / go (subjunctive)' },
  { pt: 'abre', en: 'opens' },
  { pt: 'queria', en: 'I wanted / I would like' },
  { pt: 'ingressos', en: 'tickets' },
  { pt: 'turístico', en: 'tourist / touristic' },
  { pt: 'famoso', en: 'famous' },
  { pt: 'wi-fi', en: 'Wi-Fi' },
  { pt: 'pro', en: 'to the / for the' },
  { pt: 'passaporte', en: 'passport' },
  { pt: 'médico', en: 'doctor / medical' },
  { pt: 'alugar', en: 'to rent' },
  { pt: 'chip', en: 'SIM card / chip' },
  { pt: 'portão', en: 'gate' },
  { pt: 'embarque', en: 'boarding' },
  { pt: 'quinze', en: 'fifteen', forms: ['15'] },
  { pt: 'despachar', en: 'to check / to dispatch' },
  { pt: 'maravilhoso', en: 'wonderful' },
  { pt: 'mudar', en: 'to change' },
  { pt: 'cancelar', en: 'to cancel' },
  { pt: 'chama', en: 'is called / calls' },
  { pt: 'Ana', en: 'Ana' },
  { pt: 'churrasco', en: 'barbecue' },
  { pt: 'conhece', en: 'knows / meets' },
  { pt: 'desde', en: 'since' },
  { pt: 'avós', en: 'grandparents' },
  { pt: 'casado', en: 'married' },
  { pt: 'unida', en: 'united / close-knit' },
  { pt: 'tal', en: 'such / what about' },
  { pt: 'cinema', en: 'movie theater' },
  { pt: 'segunda', en: 'Monday / second' },
  { pt: 'aniversário', en: 'birthday' },
  { pt: 'sobrinha', en: 'niece' },
  { pt: 'vejo', en: 'I see' },
  { pt: 'tios', en: 'uncles' },
  { pt: 'sogros', en: 'in-laws' },
  { pt: 'adora', en: 'adores / loves' },
  { pt: 'pescar', en: 'to fish' },
  { pt: 'fui', en: 'I went / I was' },
  { pt: 'toda', en: 'all / entire (fem.)' },
  { pt: 'reúne', en: 'gathers / brings together' },
  { pt: 'Natal', en: 'Christmas' },
  { pt: 'der', en: 'give / work out (subjunctive)' },
  { pt: 'padrinho', en: 'best man / godfather' },
  { pt: 'casamento', en: 'wedding / marriage' },
  { pt: 'planejando', en: 'planning' },
  { pt: 'festa', en: 'party' },
  { pt: 'chocolate', en: 'chocolate' },
  { pt: 'infância', en: 'childhood' },
  { pt: 'apoiam', en: 'support' },
  { pt: 'todas', en: 'all (fem. pl.)' },
  { pt: 'decisões', en: 'decisions' },
  { pt: 'nossos', en: 'our (masc. pl.)' },
  { pt: 'sobrinho', en: 'nephew' },
  { pt: 'acabou', en: 'ended / just finished' },
  { pt: 'ótimos', en: 'great / excellent (pl.)' },
  { pt: 'conselhos', en: 'advice' },
  { pt: 'ri', en: 'I laughed' },
  { pt: 'considero', en: 'I consider' },
  { pt: 'ligar', en: 'to call' },
  { pt: 'Julia', en: 'Julia' },
  { pt: 'amizade', en: 'friendship' },
  { pt: 'bonita', en: 'beautiful' },
  { pt: 'grávida', en: 'pregnant' },
  { pt: 'menina', en: 'girl' },
  { pt: 'nasceu', en: 'was born' },
  { pt: 'madrinha', en: 'godmother' },
  { pt: 'apresentou', en: 'introduced / presented' },
  { pt: 'grupo', en: 'group' },
  { pt: 'mesmo', en: 'same / even' },
  { pt: 'cada', en: 'each' },
  { pt: 'ocupado', en: 'busy' },
  { pt: 'questão', en: 'matter / point / question' },
  { pt: 'levantar', en: 'to get up / to lift' },
  { pt: 'despertar', en: 'to wake up' },
  { pt: 'xícara', en: 'cup / mug' },
  { pt: 'sair', en: 'to leave / to go out' },
  { pt: 'terrível', en: 'terrible' },
  { pt: 'escritório', en: 'office' },
  { pt: 'e-mails', en: 'emails' },
  { pt: 'muitas', en: 'many (fem. pl.)' },
  { pt: 'trago', en: 'I bring' },
  { pt: 'marmita', en: 'packed lunch' },
  { pt: 'saio', en: 'I leave / go out' },
  { pt: 'direto', en: 'straight / directly' },
  { pt: 'expediente', en: 'work shift / office hours' },
  { pt: 'voltando', en: 'returning / coming back' },
  { pt: 'tiro', en: 'I take / remove' },
  { pt: 'jantamos', en: 'we have dinner' },
  { pt: 'lavo', en: 'I wash' },
  { pt: 'seriado', en: 'TV series' },
  { pt: 'TV', en: 'TV' },
  { pt: 'leio', en: 'I read' },
  { pt: 'nas', en: 'in the / at the (fem. pl.)' },
  { pt: 'ajudo', en: 'I help' },
  { pt: 'converso', en: 'I talk / chat' },
  { pt: 'sobre', en: 'about' },
  { pt: 'cachorro', en: 'dog' },
  { pt: 'passear', en: 'to walk / stroll' },
  { pt: 'sono', en: 'sleep / sleepiness' },
  { pt: 'hora', en: 'time / hour' },
  { pt: 'deitar', en: 'to lie down' },
  { pt: 'esqueça', en: 'forget' },
  { pt: 'despertador', en: 'alarm clock' },
  { pt: 'coloco', en: 'I put' },
  { pt: 'carregar', en: 'to charge / to carry' },
  { pt: 'onze', en: 'eleven' },
  { pt: 'bons', en: 'good (pl.)' },
  { pt: 'aos', en: 'to the / at the (masc. pl.)' },
  { pt: 'sábados', en: 'Saturdays' },
  { pt: 'limpeza', en: 'cleaning' },
  { pt: 'preparo', en: 'I prepare' },
  { pt: 'roupas', en: 'clothes' },
  { pt: 'seguinte', en: 'following / next' },
  { pt: 'durante', en: 'during' },
  { pt: 'caminhada', en: 'walk' },
  { pt: 'ouço', en: 'I listen' },
  { pt: 'enquanto', en: 'while' },
  { pt: 'organizo', en: 'I organize' },
  { pt: 'anterior', en: 'previous' },
  { pt: 'acabo', en: 'I end up / I finish' },
  { pt: 'atrasando', en: 'running late / delaying' },
  { pt: 'foco', en: 'focus' },
  { pt: 'alegria', en: 'joy' },
  { pt: 'animado', en: 'excited' },
  { pt: 'ótimo', en: 'great' },
  { pt: 'humor', en: 'mood' },
  { pt: 'deixa', en: 'leaves / makes' },
  { pt: 'contente', en: 'happy / pleased' },
  { pt: 'pena', en: 'pity / shame' },
  { pt: 'desapontado', en: 'disappointed' },
  { pt: 'baixo', en: 'low / down' },
  { pt: 'coração', en: 'heart' },
  { pt: 'partido', en: 'broken' },
  { pt: 'fique', en: 'stay / be (subjunctive)' },
  { pt: 'perdeu', en: 'lost' },
  { pt: 'acredito', en: 'I believe' },
  { pt: 'furiosa', en: 'furious' },
  { pt: 'situação', en: 'situation' },
  { pt: 'saco', en: 'what a drag / bag' },
  { pt: 'progresso', en: 'progress' },
  { pt: 'medo', en: 'fear' },
  { pt: 'pavor', en: 'dread' },
  { pt: 'altura', en: 'height' },
  { pt: 'assustado', en: 'scared' },
  { pt: 'barulho', en: 'noise' },
  { pt: 'preocupado', en: 'worried' },
  { pt: 'apresentações', en: 'presentations' },
  { pt: 'barriga', en: 'belly / stomach' },
  { pt: 'preocupe', en: 'worry' },
  { pt: 'surpresa', en: 'surprise' },
  { pt: 'chocado', en: 'shocked' },
  { pt: 'esperava', en: 'expected' },
  { pt: 'impressionada', en: 'impressed' },
  { pt: 'talento', en: 'talent' },
  { pt: 'incrível', en: 'incredible' },
  { pt: 'amo', en: 'I love' },
  { pt: 'carinho', en: 'affection' },
  { pt: 'calmo', en: 'calm' },
  { pt: 'vergonha', en: 'embarrassment / shame' },
  { pt: 'confuso', en: 'confused' },
  { pt: 'instruções', en: 'instructions' },
  { pt: 'orgulhoso', en: 'proud' },
  { pt: 'culpada', en: 'guilty' },
  { pt: 'ligado', en: 'called / connected' },
  { pt: 'exausto', en: 'exhausted' },
  { pt: 'otimista', en: 'optimistic' },
  { pt: 'minuto', en: 'minute' },
  { pt: 'significa', en: 'means' },
  { pt: 'informar', en: 'to inform' },
  { pt: 'saída', en: 'exit / output' },
  { pt: 'importaria', en: 'would mind' },
  { pt: 'mãozinha', en: 'little hand / little help' },
  { pt: 'será', en: 'will it be / is it' },
  { pt: 'sei', en: 'I know' },
  { pt: 'exemplo', en: 'example' },
  { pt: 'incômodo', en: 'inconvenience / bother' },
  { pt: 'mas', en: 'but' },
  { pt: 'entendeu', en: 'understood' },
  { pt: 'disse', en: 'said' },
  { pt: 'dúvida', en: 'doubt' },
  { pt: 'escreve', en: 'writes / spells' },
  { pt: 'conseguindo', en: 'managing / being able' },
  { pt: 'conectar', en: 'to connect' },
  { pt: 'informação', en: 'information' },
  { pt: 'emprestar', en: 'to lend' },
  { pt: 'carregador', en: 'charger' },
  { pt: 'teria', en: 'would have / would there be' },
  { pt: 'verificar', en: 'to check / verify' },
  { pt: 'direito', en: 'properly / right' },
  { pt: 'consertar', en: 'to fix' },
  { pt: 'documento', en: 'document' },
  { pt: 'enviado', en: 'sent' },
  { pt: 'provar', en: 'to try / to taste / to prove' },
  { pt: 'embrulhar', en: 'to wrap' },
  { pt: 'sacar', en: 'to withdraw' },
  { pt: 'débito', en: 'debit' },
  { pt: 'parcelar', en: 'to pay in installments' },
  { pt: 'quantas', en: 'how many (fem. pl.)' },
  { pt: 'juros', en: 'interest' },
  { pt: 'troco', en: 'change' },
  { pt: 'cem', en: 'one hundred' },
  { pt: 'CPF', en: 'taxpayer ID' },
  { pt: 'política', en: 'policy' },
  { pt: 'promoção', en: 'sale / promotion' },
  { pt: 'aproximação', en: 'contactless / proximity' },
  { pt: 'máquina', en: 'machine / card machine' },
  { pt: 'fiscal', en: 'tax / fiscal' },
  { pt: 'recibo', en: 'receipt' },
  { pt: 'encontro', en: 'I find / encounter' },
  { pt: 'seção', en: 'section' },
  { pt: 'negociável', en: 'negotiable' },
  { pt: 'liquidação', en: 'clearance sale' },
  { pt: 'via', en: 'via / by' },
  { pt: 'valor', en: 'amount / value' },
  { pt: 'quero', en: 'I want' },
  { pt: 'confirmar', en: 'to confirm' },
  { pt: 'garantia', en: 'warranty' },
  { pt: 'cobre', en: 'covers' },
  { pt: 'troca', en: 'exchange' },
  { pt: 'fabricação', en: 'manufacturing' },
  { pt: 'Copacabana', en: 'Copacabana' },
  { pt: 'quarteirões', en: 'blocks' },
  { pt: 'semáforo', en: 'traffic light' },
  { pt: 'logo', en: 'right away / soon' },
  { pt: 'ali', en: 'there' },
  { pt: 'lado', en: 'side' },
  { pt: 'avenida', en: 'avenue' },
  { pt: 'prédio', en: 'building' },
  { pt: 'passe', en: 'go past / pass' },
  { pt: 'terceira', en: 'third (fem.)' },
  { pt: 'erro', en: 'mistake' },
  { pt: 'descer', en: 'to get off / to go down' },
  { pt: 'Central', en: 'Central' },
  { pt: 'linha', en: 'line' },
  { pt: 'Maracanã', en: 'Maracana' },
  { pt: 'fechou', en: 'closed' },
  { pt: 'passa', en: 'passes' },
  { pt: 'baldeação', en: 'transfer' },
  { pt: 'Uber', en: 'Uber' },
  { pt: 'parar', en: 'to stop' },
  { pt: 'pedi', en: 'I asked / ordered' },
  { pt: 'aplicativo', en: 'app' },
  { pt: 'posto', en: 'station / post' },
  { pt: 'gasolina', en: 'gasoline' },
  { pt: 'estacionar', en: 'to park' },
  { pt: 'estacionamento', en: 'parking lot' },
  { pt: 'limite', en: 'limit' },
  { pt: 'velocidade', en: 'speed' },
  { pt: 'nesta', en: 'in this / on this (fem.)' },
  { pt: 'certa', en: 'correct / right (fem.)' },
  { pt: 'avise', en: 'let me know / inform me' },
  { pt: 'estreita', en: 'narrow (fem.)' },
  { pt: 'responder', en: 'to answer' },
  { pt: 'trabalhando', en: 'working' },
  { pt: 'relatório', en: 'report' },
  { pt: 'tarefa', en: 'task' },
  { pt: 'home office', en: 'remote work' },
  { pt: 'entrevista', en: 'interview' },
  { pt: 'chefe', en: 'boss' },
  { pt: 'exigente', en: 'demanding' },
  { pt: 'impressora', en: 'printer' },
  { pt: 'quebrou', en: 'broke' },
  { pt: 'adiada', en: 'postponed (fem.)' },
  { pt: 'história', en: 'history / story' },
  { pt: 'exame', en: 'exam' },
  { pt: 'professor', en: 'teacher / professor' },
  { pt: 'explicou', en: 'explained' },
  { pt: 'biblioteca', en: 'library' },
  { pt: 'preferida', en: 'favorite (fem.)' },
  { pt: 'Administração', en: 'business administration' },
  { pt: 'semestre', en: 'semester' },
  { pt: 'faltei', en: 'I missed / I was absent' },
  { pt: 'TCC', en: 'thesis / capstone project' },
  { pt: 'notas', en: 'grades' },
  { pt: 'saíram', en: 'came out / were released' },
  { pt: 'difícil', en: 'difficult' },
  { pt: 'conciliar', en: 'to balance / to reconcile' },
  { pt: 'marketing', en: 'marketing' },
  { pt: 'digital', en: 'digital' },
  { pt: 'consegui', en: 'I got / I managed' },
  { pt: 'software', en: 'software' },
  { pt: 'computador', en: 'computer' },
  { pt: 'travou', en: 'froze / crashed' },
  { pt: 'estuda', en: 'studies' },
  { pt: 'focar', en: 'to focus' },
  { pt: 'apertado', en: 'tight' },
  { pt: 'formar', en: 'to graduate / to form' },
  { pt: 'começa', en: 'starts' },
  { pt: 'folga', en: 'day off' },
  { pt: 'perder', en: 'to lose / to miss' },
  { pt: 'férias', en: 'vacation' },
  { pt: 'ambiente', en: 'environment' },
  { pt: 'passei', en: 'I spent / I passed' },
  { pt: 'carga', en: 'load / workload' },
  { pt: 'horária', en: 'hourly / schedule-related' },
  { pt: 'temos', en: 'we have' },
  { pt: 'curto', en: 'short' },
  { pt: 'precisamos', en: 'we need' },
  { pt: 'beleza', en: 'okay / beauty' },
  { pt: 'hein', en: 'huh / right' },
  { pt: 'tranquilo', en: 'calm / all good' },
  { pt: 'calor', en: 'heat' },
  { pt: 'chover', en: 'to rain' },
  { pt: 'melhorou', en: 'improved / got better' },
  { pt: 'moro', en: 'I live' },
  { pt: 'plano', en: 'plan' },
  { pt: 'qualquer', en: 'any' },
  { pt: 'livre', en: 'free / available' },
  { pt: 'assistiu', en: 'watched' },
  { pt: 'tipo', en: 'type / kind' },
  { pt: 'curte', en: 'likes / is into' },
  { pt: 'torce', en: 'roots / cheers' },
  { pt: 'time', en: 'team' },
  { pt: 'bebida', en: 'drink' },
  { pt: 'demorei', en: 'I took a while' },
  { pt: 'gostei', en: 'I liked' },
  { pt: 'falou', en: 'said / spoke' },
  { pt: 'pois', en: 'well / then / since' },
  { pt: 'nisso', en: 'by the way / in that' },
  { pt: 'tenha', en: 'have (subjunctive)' },
  { pt: 'tiver', en: 'have (future subjunctive)' },
  { pt: 'tempinho', en: 'little time' },
];

function inferDifficulty(text: string, override?: 1 | 2 | 3 | 4 | 5): 1 | 2 | 3 | 4 | 5 {
  if (override) {
    return override;
  }

  if (/\d/.test(text)) {
    return 1;
  }

  if (text.includes(' ') || text.includes('-')) {
    return text.length > 12 ? 3 : 2;
  }

  if (/[ãõâêôáéíóúç]/i.test(text) || /nh|lh|rr/i.test(text)) {
    return text.length > 8 ? 4 : 3;
  }

  if (text.length <= 4) {
    return 1;
  }

  if (text.length <= 8) {
    return 2;
  }

  return 3;
}

function inferDifficultForEnglish(
  text: string,
  override?: boolean
): boolean {
  if (override !== undefined) {
    return override;
  }

  return /[ãõâêôáéíóúç]|nh|lh|rr|ão|õe|õe|ões|ãe|ção/i.test(text);
}

function inferPartOfSpeech(text: string): string {
  if (text.includes(' ') || text.includes('-') || /\d/.test(text)) {
    return 'phrase';
  }

  return 'support';
}

export const COVERAGE_RAW_WORDS: RawWord[] = COVERAGE_WORD_SPECS.map((spec, index) => ({
  id: `coverage_${String(index + 1).padStart(3, '0')}`,
  pt: spec.pt,
  forms: spec.forms,
  en: spec.en,
  pos: inferPartOfSpeech(spec.pt),
  category: 'misc_common_words',
  difficulty: inferDifficulty(spec.pt, spec.difficulty),
  difficult_for_english: inferDifficultForEnglish(spec.pt, spec.difficultForEnglish),
}));
