/**
 * Canonical mapping between a token's resolution type and its trust bucket.
 *
 * HIGH    curated data (exact or lemma match against masterWords.json)
 * MEDIUM  generated by the heuristic phonemeMapper — audible but unreviewed
 * LOW     nothing resolved — pipeline flagged the token for manual review
 *
 * The validator uses this map to prevent drift (e.g. accidentally shipping
 * a token labeled high-confidence when its resolution was heuristic).
 */

import type {
  TokenConfidence,
  TokenResolutionType,
} from './types/customSentence';

export const CONFIDENCE_BY_RESOLUTION: Record<TokenResolutionType, TokenConfidence> = {
  exact_match: 'high',
  lemma_match: 'high',
  generated: 'medium',
  unresolved: 'low',
};

export function confidenceForResolution(type: TokenResolutionType): TokenConfidence {
  return CONFIDENCE_BY_RESOLUTION[type];
}
