import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { PTBR_MINIMAL_PAIRS } from '../src/lib/coaching/minimalPairs.ptbr';

type AudioIndexEntry = {
  voices?: {
    ptbr_male?: string;
    ptbr_female?: string;
  };
};

export type TourFacts = {
  sentences: number;
  words: number;
  phonemeMetadataEntries: number;
  confusionPatternTags: number;
  minimalPairPrompts: number;
  dualVoiceAudioIndexEntries: number;
};

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = path.join(repoRoot, 'src/pages/tour/tourFacts.generated.ts');

async function readJson<T>(relativePath: string): Promise<T> {
  return JSON.parse(await readFile(path.join(repoRoot, relativePath), 'utf8')) as T;
}

export async function deriveTourFacts(): Promise<TourFacts> {
  const [sentences, words, phonemes, audioIndex] = await Promise.all([
    readJson<unknown[]>('data/masterSentences.json'),
    readJson<unknown[]>('data/masterWords.json'),
    readJson<unknown[]>('data/phoneme_metadata.json'),
    readJson<Record<string, AudioIndexEntry>>('data/audio_index.json'),
  ]);

  const confusionPatternTags = new Set(
    PTBR_MINIMAL_PAIRS.flatMap((pair) => pair.tags),
  );
  const dualVoiceAudioIndexEntries = Object.values(audioIndex).filter(
    (entry) => entry.voices?.ptbr_male && entry.voices?.ptbr_female,
  ).length;

  return {
    sentences: sentences.length,
    words: words.length,
    phonemeMetadataEntries: phonemes.length,
    confusionPatternTags: confusionPatternTags.size,
    minimalPairPrompts: PTBR_MINIMAL_PAIRS.length,
    dualVoiceAudioIndexEntries,
  };
}

export function renderTourFacts(facts: TourFacts): string {
  return `/**
 * Generated by scripts/generateTourFacts.ts from repository data.
 * Run \`npm run tour:facts\` after changing the underlying datasets.
 */
export const TOUR_FACTS = ${JSON.stringify(facts, null, 2)} as const;
`;
}

async function main(): Promise<void> {
  const facts = await deriveTourFacts();
  const rendered = renderTourFacts(facts);

  if (process.argv.includes('--check')) {
    const current = await readFile(outputPath, 'utf8').catch(() => '');
    if (current !== rendered) {
      throw new Error('Tour facts are stale. Run `npm run tour:facts` and commit the result.');
    }
    console.log('Tour facts are current.');
    return;
  }

  await writeFile(outputPath, rendered, 'utf8');
  console.log(`Wrote ${path.relative(repoRoot, outputPath)}.`);
}

const directEntry = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : '';
if (directEntry === import.meta.url) {
  void main();
}
