/**
 * Generated by scripts/generateTourFacts.ts from repository data.
 * Run `npm run tour:facts` after changing the underlying datasets.
 */
export const TOUR_FACTS = {
  "sentences": 593,
  "words": 974,
  "phonemeMetadataEntries": 36,
  "confusionPatternTags": 13,
  "minimalPairPrompts": 42,
  "dualVoiceAudioIndexEntries": 1567
} as const;
