import { useState, useRef, useEffect } from 'react';
import { getWordAudioPath, type WordVoice } from '@/lib/wordAudioPaths';

interface WordAudioButtonProps {
  wordId: string;
  voice?: WordVoice;
  label?: string;
  compact?: boolean;
  className?: string;
}

/**
 * Button component for playing TTS-generated word audio.
 * Uses the audio files generated by generateWordAudio.ts script.
 */
export default function WordAudioButton({
  wordId,
  voice = 'male',
  label,
  compact = false,
  className = '',
}: WordAudioButtonProps) {
  const [isPlaying, setIsPlaying] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  // Reset audio when wordId or voice changes
  useEffect(() => {
    if (audioRef.current) {
      audioRef.current.pause();
      audioRef.current.currentTime = 0;
      audioRef.current.src = '';
      setIsPlaying(false);
    }
  }, [wordId, voice]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (audioRef.current) {
        audioRef.current.pause();
        audioRef.current = null;
      }
    };
  }, []);

  const handlePlay = () => {
    // Stop if already playing
    if (isPlaying && audioRef.current) {
      audioRef.current.pause();
      audioRef.current.currentTime = 0;
      setIsPlaying(false);
      return;
    }

    // Create audio element if it doesn't exist
    if (!audioRef.current) {
      audioRef.current = new Audio();
      
      audioRef.current.addEventListener('ended', () => {
        setIsPlaying(false);
      });
      
      audioRef.current.addEventListener('error', () => {
        const error = audioRef.current?.error;
        const errorMsg = error 
          ? `Error ${error.code}: ${error.message || 'Unknown error'}`
          : 'Unknown error';
        console.error(`Failed to play audio for word "${wordId}" (${voice}) at path "${getWordAudioPath(wordId, voice)}":`, errorMsg);
        setIsPlaying(false);
      });
    }

    // Set source and play
    const audioPath = getWordAudioPath(wordId, voice);
    
    try {
      audioRef.current.src = audioPath;
      
      // Use play() promise and handle errors
      const playPromise = audioRef.current.play();
      
      if (playPromise !== undefined) {
        playPromise
          .then(() => {
            // Audio started playing successfully
            setIsPlaying(true);
          })
          .catch((error) => {
            // Auto-play was prevented or other error
            console.error(`Failed to play audio for word "${wordId}" (${voice}):`, error);
            setIsPlaying(false);
          });
      } else {
        // Fallback for older browsers
        setIsPlaying(true);
      }
    } catch (error) {
      console.error(`Error setting audio source for word "${wordId}" (${voice}):`, error);
      setIsPlaying(false);
    }
  };

  const icon = isPlaying ? '⏸' : '▶';
  const displayLabel = label || (voice === 'male' ? '👨' : '👩');

  if (compact) {
    return (
      <button
        onClick={handlePlay}
        className={`w-8 h-8 rounded-full flex items-center justify-center text-xs transition-all ${
          isPlaying
            ? 'bg-primary-500 text-white shadow-lg animate-pulse'
            : 'bg-primary-100 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 hover:bg-primary-200 dark:hover:bg-primary-900/50'
        } ${className}`}
        title={`Play ${voice} pronunciation`}
        aria-label={`Play ${voice} pronunciation of word`}
      >
        {displayLabel}
      </button>
    );
  }

  return (
    <button
      onClick={handlePlay}
      className={`btn btn-sm ${
        isPlaying ? 'btn-primary' : 'btn-outline-primary'
      } ${className}`}
      title={`Play ${voice} pronunciation`}
    >
      <span className="mr-2">{icon}</span>
      {displayLabel}
    </button>
  );
}

